services:
  redis:
    image: redis:7.0.12-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis_data: